version: "2"
linters:
  enable:
    - errcheck
    - exhaustive
    - exhaustruct
    - forbidigo
    - gocognit
    - gocritic
    - godot
    - gosec
    - govet
    - ineffassign
    - misspell
    - nlreturn
    - paralleltest
    - perfsprint
    - prealloc
    - reassign
    - revive
    - sloglint
    - staticcheck
    - unused
  settings:
    gocognit:
      min-complexity: 15
    perfsprint:
      strconcat: false
