baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

disableKinds = ['taxonomy', 'term']

[params]
  shortName = 'My New Hugo Site'
  description = 'A new Hugo site'
  backgroundColor = '#ffffff'
  themeColor = '#000000'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Documentation'
    pageRef = '/docs'
    weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

[outputs]
  home = ['html', 'rss', 'webappmanifest']

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
